### PR TITLE
Added services to set wifi / discovery devices, set time schedule, se…

### PR DESCRIPTION
**Pull request by mcc05**
Added services to set wifi / discovery devices, set time schedule, set advanced parameters, remotelock etc. and Experimental Discovery

**Wifi Setup/and device discovery.**
Using the HA Service climate.hysen_config_wifi, with the following json 
{"ssid":"yoursid","password":"yourpassword","sectype":4,"timeout":5} will setup Hysen devices (if in setup mode) and will report back on discovery devices, note sectype (0 - none, 1 = WEP, 2 = WPA1, 3 = WPA2, 4 = WPA1/2)

**Set Advanced Parameters**
Using the HA Service climate.hysen_set_timeschedule, with the following json 
{"entity_id":"yourentity_id","poweron_mem":"1"} for example will change the advanced parameters.

**Time Schedule Set**
Using the HA Service climate.hysen_set_advanced, with the following json
{"entity_id":"yourentity_id",
    "week_period1_start":"06:30", 
    "week_period1_temp":"20.5",
    "week_period2_start":"09:00",
    "week_period2_temp":"17.0",
    "week_period3_start":"13:00",
    "week_period3_temp":"17.0",
    "week_period4_start":"13:00",
    "week_period4_temp":"17.0",
    "week_period5_start":"17:00",
    "week_period5_temp":"20.5",
    "week_period6_start":"22:00",
    "week_period6_temp":"17.0",
    "weekend_period1_start":"7:30",
    "weekend_period1_temp":"20.5",
    "weekend_period2_start":"22:30",
    "weekend_period2_temp":"17.0"}
will allow the setting of the time schedule

**RemoteLock**
Using the HA Service climate.hysen_set_advanced, with the following json
{"entity_id":"yourentity_id","remotelock":1} will set the remote lock function 0 to unlock

**Experimental Discovery on HA startup.**
If only MAC Address is specified in HA config, the setup will attempt to discovery the Hysen device and IP, however

### CODE REVIEW

**Comment by mairas** [comment]
Did you forget to include some files in the PR? I don't see any changes related to most of the features you mentioned?

**Comment by mcc05** [comment]
Sorry didn't merge

**Comment by mairas** [comment]
Doesn't work for me. Now I'm getting:

```
AttributeError: module 'homeassistant.helpers.config_validation' has no attribute 'comp_entity_ids'
```

**Comment by mcc05** [comment]
Hi does it say which line? thats strange what version of HA are you running ? comp_entity_ids are used all over the place...

**Pull request merged**
